# Package Registry

[[package]]
name = "hello"
version = "1.0.0"
id = "hello"
pkgversion = 1

location = "packages/hello-1.0.0.zip"

sha256 = "d7c8f..."
blake3 = "9a32b..."

[[package]]
name = "editor"
version = "2.3.1"
id = "hello2"
pkgversion = 1

location = "packages/editor-2.3.1.zip"

sha256 = "a1234..."
blake3 = "b5678..."
