[package]
name = "easy-git-ignore"
version = "0.1.0"
edition = "2024"
authors = ["Shadowdara"]
readme = "README.md"
description = "a tool to add stuff to the git ignore the cool way"
license = "Apache-2.0"
include = ["LICENSE", "README.md", "Cargo.toml", "/src/", "build.rs"]
keywords = ["git", "ignore", "samengine"]
repository = "https://github.com/shadowdara/samengine"

[[bin]]
name = "git-ign"
path = "src/main.rs"

[dependencies]

[build-dependencies]
cc = "1"

[profile.release]
opt-level = 3       # 0 -> no optimizing, 3 -> max speed
lto = "fat"         # oder "thin" für schnelleren Build
codegen-units = 1   # bessere Optimierung, aber langsamerer Compile
panic = "abort"     # spart etwas Platz, leicht schneller
strip = true        # entfernt Debug-Symbole (optional)
debug = false
incremental = false
