name: release

on:
  push:
    tags:
      - "samtool-v*"

permissions:
  contents: write

jobs:
  build:

    strategy:
      matrix:
        include:

          - target: x86_64-unknown-linux-gnu
            package: linux-x64
            binary: samtool

          - target: aarch64-unknown-linux-gnu
            package: linux-arm64
            binary: samtool

          - target: x86_64-apple-darwin
            package: darwin-x64
            binary: samtool

          - target: aarch64-apple-darwin
            package: darwin-arm64
            binary: samtool

          - target: x86_64-pc-windows-msvc
            package: win32-x64
            binary: samtool.exe

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - uses: taiki-e/setup-cross-action@v1

      - name: Build
        run: |
          cross build \
            -p samtool \
            --release \
            --target ${{ matrix.target }}

      - name: Copy binary
        run: |
          cp \
          target/${{ matrix.target }}/release/${{ matrix.binary }} \
          npm/${{ matrix.package }}/${{ matrix.binary }}

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org

      - name: Publish platform package
        run: |
          cd npm/${{ matrix.package }}
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-cli:

    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org

      - run: |
          cd npm/cli
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
